### ISSUE TITLE
Valorar viabilidad de usar los componentes gráficos libres 

### ISSUE THREAD

**Issue by clopezno** [Sonia95LG/POODLEapp#10]
Valorar si con los componentes libres de Vaddin y decidir si son suficientes para realizar la aplicación. 
Basarse en los resultados de #9 

Seleccionar algun caso de uso del TFG como prototipo de interface.

**Comment by Sonia95LG** [comment]
28/02 Nota01 : Para poder usar cada uno de los componentes que necesitamos o bien los instalamos uno a uno o deberemos cargar el código correspondiente en una clase aparte o en la misma clase donde queramos usarlo (recomendada la primera puesto que vamos a usar varios elementos y eso hará que el código no sea fácil de interpretar)

**Comment by Sonia95LG** [comment]
05/03 : No veo claro que se puedan usar correctamente los componentes, libres o no, de Vaadin puesto que suponen no solo una instalación de paquetes "masiva" sino que muchos de ellos (expuestos en la página de Vaadin) después no funcionan con la última versión.
