### ISSUE TITLE
Componentes libres + Layout Vaadin

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#13]
Seguir trabajando y probando los componentes de Vaadin y los layout que puedan ser más útiles para el proyecto.

**Comment by Sonia95LG** [comment]
Problemas encontrados tras el commit 8a59d66

- Algunos de los componentes libres tienen SOLO opción HTML (como el menú desplegable)
- DatePicker (en la web) no existe, por lo que hay que utilizar DateField
- No existe un componente para poner la hora. Aunque se solucione con una casilla de texto, esto dificulta la posterior lectura de datos ya que habrá que hacer un procesamiento sobre la misma
- El diseño no es muy cómodo, y no se puede cambiar porque las opciones que se ofrecen en la web de Vaadin no funcionan

**Comment by clopezno** [comment]
He hablado con @mjuez, tiene experiencia en desarrollo con Vaddin. Le he comentado algunos problemas que me has ido comentando  sobre Componentes y Layout.  Me ha dado los siguientes consejos

Hay un libro de Vaadin (versión 8) que ayuda a entender todo el framework. Lo puedes descargar gratis desde aquí. https://vaadin.com/docs/v10/index.html#book-of-vaadin
Me ha indicado que hay componentes de que son de pago pero los layouts son libres. 

He visto que la última versión estable es la 8, y que hay versión 10 beta, no sé cuál estará utilizando tu alumna, pero yo me inclinaría por la 8, por estabilidad y por documentación.

Si tenéis cualquier problema concreto ya sabes que estoy disponible, puedo reunirme con vosotros e intentar aportar alguna idea que le pueda servir de ayuda, aunque esté un par de versiones desactualizado supongo que el funcionamiento básico de layouts y tal será muy similar.

**Comment by Sonia95LG** [comment]
He revisado algunos de los proyectos iniciados como demos o pruebas para los diferentes componentes y, tras cerciorarme de que la versión que utilizo es la 8 he probado de nuevo a utilizar los componentes gratuitos. 
Sigue habiendo fallos con algunos de los métodos de componentes que se exponen en la web
