### ISSUE TITLE
Formación en Vaadin

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#3]

**Comment by Sonia95LG** [comment]
Commit correspondiente a la creación de una demo y la subida de una imagen resultante: 57f34e6163ed3b23be26f6c490b224de0f43faf4

**Comment by Sonia95LG** [comment]
Problemas encontrados al hacer el commit 0ab06fa8da56d3c6b8cf5ed2440be5c4d4fcbacb : 

- La licencia para usar el Panel de Diseño cuesta 790$ y sino tenemos una Licencia de Prueba de 14 días

- Existen tutoriales pero en ninguno se enseña un ejemplo útil para poder aprender a usar el panel y las paletas, lo cual dificulta su aprendizaje

- Se ha realizado una prueba siguiendo un código html que aparece en una de las webs de guía y el resultado no se parece nada a lo que se expone en la web

**Comment by Sonia95LG** [comment]
Webs consultadas para la parte de Diseño:

https://vaadin.com/docs/v8/designer/designer-designing.html

https://vaadin.com/docs/v8/designer/designer-getting-started.html#designer.getting-started.design

https://vaadin.com/docs/v8/designer/designer-wiring.html

**Comment by clopezno** [comment]
Cimple objetivos issue
