### ISSUE TITLE
Vista Coordinador

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#40]
Vista del coordinador, que se compone de un calendario completo y de un listado con las semanas y la carga de cada una de ellas.
Además, tendrá un botón que de acceso al editor de Calendar de Google, por si fuese necesario hacer modificaciones de pruebas.

**Comment by Sonia95LG** [comment]
Se ha incluido ya la vista del calendario completo. Falta el listado de las semanas con su correspondiente carga semanal.

¿Cuáles son los rangos en los que se debe mover una semana? ¿Hasta que porcentaje sería un nivel "verde"? ¿Hasta qué un nivel naranja? ¿Hasta qué porcentaje un nivel rojo, el cual implica cambiar las pruebas?

**Comment by clopezno** [comment]
Los rangos deberían ser configurados desde un fichero. 
Los valores por defecto por curso pueden ser:
- verde [20% - 70%]
- naranja [0%-20%] y [70%-100%]
- rojo mayor que 100%

Invariante : la suma de los rangos semanales debería ser igual al número de asignaturas  por 100%. Si se tiene en cuenta la segunda convocatoria sería número de asignaturas por 200% (100% primera convocatoria + 100% segunda convocatoria)

**Comment by Sonia95LG** [comment]
¿Por qué es naranja que haya de 0 a 20% de carga una semana? Solo se me ocurre que sea porque una semana poco cargada implica otras muy cargadas, pero hay meses en los que simplemente no hay pruebas (los de inicio de cuatrimestre por ejemplo)
