### ISSUE TITLE
Formación Maven

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#5]

**Comment by Sonia95LG** [comment]
15/02: Se ha hecho la comprobación de que la instalación era correcta y se ha comprobado su uso gracias a la aplicación de Vaadin realizada a modo de prueba

**Comment by clopezno** [comment]
POM con compilación de Vaddin y depliegue en Heroku.
En fituras versiones se utilizará para pruebas, integración contínua con Trabis y  aseguramiento de la calidad.
