### ISSUE TITLE
Memoria del proyecto

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#60]
Redactar la memoria del proyecto al completo, dejando para el final todas las imágenes de prueba.

**Comment by Sonia95LG** [comment]
Las referencias a la bibliografía salen en rojo ¿por qué?

**Comment by Sonia95LG** [comment]
No se si estoy redundando información en la Memoria principal y en los Anexos ya que hay cosas que encajan perfectamente tanto en "Aspectos relevantes del proyecto" y en el anexo dedicado al Diseño.

**Comment by Sonia95LG** [comment]
¿Es correcto poner una tabla con todos los pares usuario/contraseña en el manual del administrador?

**Comment by clopezno** [comment]
- **No se si estoy redundando información en la Memoria principal y en los Anexos ya que hay cosas que encajan perfectamente tanto en "Aspectos relevantes del proyecto" y en el anexo dedicado al Diseño.**

La memoria y los anexos pueden tener información redundante porque son documentos indepenedientes. Pero el nivel de detalle en los anexos debería ser mayor que en la memoria.

- **¿Es correcto poner una tabla con todos los pares usuario/contraseña en el manual del administrador?**
No si  el estado de la aplicación fuese de explotación. Pero en el caso de un TFG  (estado prototipo) es necesario incluir esta información para  poder probar la funcionalidad de la aplicación.

- **Las referencias a la bibliografía salen en rojo ¿por qué?**
Es una opción del paquete hyperlink de LateX para resaltar el texto que contiene  hiperenlaces.
Si no recuerdo mal, para eliminarlo en impresión era tan fácil como añadir la opción `colorlinks=false ` en el paquete:
> \usepackage[colorlinks=false]{hyperref}

**Comment by clopezno** [comment]
- **Tengo dudas sobre algunos de los apartados de la Memoria. ¿En Diseño procedimental y Diseño arquitectónico qué hay que explicar? ¿Y en Plan de Proyecto?**

Toma como referencia  la [documentación de este TFG](https://github.com/davidmigloz/go-bees/blob/master/docs/latex/anexos.pdf)   para que te ayude a entender y redactar los contenidos de esos apartados.
