### ISSUE TITLE
Diseño gráfico de la aplicación

### ISSUE THREAD

**Issue by Sonia95LG** [Sonia95LG/POODLEapp#61]
Aplicar estilos a la aplicación

**Comment by Sonia95LG** [comment]
Colorear tabla del curso: https://es.stackoverflow.com/questions/87494/color-de-td-segun-valor
https://www.lawebdelprogramador.com/foros/JavaScript/1527631-Cambiar-color-fuente-a-una-fila-de-tabla-HTML-segun-una-condicion.html

**Comment by Sonia95LG** [comment]
Páginas principales: http://www.prepbootstrap.com/bootstrap-template/feature-list

**Comment by Sonia95LG** [comment]
Login: http://www.prepbootstrap.com/bootstrap-template/bootstrap-login-form-standard

**Comment by Sonia95LG** [comment]
No salen correctamente los carácteres especiales. Ni la Ñ ni los acentos salen representados.

**Comment by clopezno** [comment]
Configura la codificación de caracteres con UTF-8 ó 16

**Comment by clopezno** [comment]
Tienes que comprobar que el fichero html y css también esté editado con esa configuración.

**Comment by Sonia95LG** [comment]
Todos los ficheros HTML y CSS tienen su correspondiente charset = UTF-8

**Comment by Sonia95LG** [comment]
Ya funciona. La clave estaba en configurar la codificación de Spring. Lo añadiré a la memoria.

spring.messages.encoding=ISO-8859-1
