### ISSUE TITLE
Componentes libres Vaddin a Layout

### ISSUE THREAD

**Issue by clopezno** [Sonia95LG/POODLEapp#9]
Desarrollar una demo con componentes libres de Vaddin y diferentes Layouts. Sólo UI.
https://vaadin.com/elements/browse

**Comment by Sonia95LG** [comment]
Se instala Node.js para poder instalar posteriormente los paquetes de Vaadin necesarios para poder usar los componentes.
https://nodejs.org/en/

**Comment by Sonia95LG** [comment]
Instalamos bower globalmente para poder instalar posteriormente los componentes.
https://vaadin.com/elements/get-started#web-components

**Comment by Sonia95LG** [comment]
Instalamos DatePicker para hacer la primera prueba de los componentes. Da un error en uno de los métodos (addValueChangeListener)
https://vaadin.com/elements/vaadin-date-picker/java-examples
